/**
 * Documentation registry for JuLC stdlib methods and ledger types.
 * Used by the Monaco hover provider and completion detail popups.
 */

export interface MethodDoc {
  signature: string;
  description: string;
}

export interface TypeDoc {
  description: string;
  fields: string[];
}

/** Static method documentation for all stdlib classes. */
export const METHOD_DOCS: Record<string, Record<string, MethodDoc>> = {
  ContextsLib: {
    trace: { signature: 'trace(String message): void', description: 'Emit a trace message for debugging' },
    getTxInfo: { signature: 'getTxInfo(ScriptContext ctx): TxInfo', description: 'Extract TxInfo from ScriptContext' },
    getRedeemer: { signature: 'getRedeemer(ScriptContext ctx): PlutusData', description: 'Extract redeemer from ScriptContext' },
    txInfoInputs: { signature: 'txInfoInputs(TxInfo txInfo): List<TxInInfo>', description: 'Get transaction inputs' },
    txInfoOutputs: { signature: 'txInfoOutputs(TxInfo txInfo): List<TxOut>', description: 'Get transaction outputs' },
    txInfoSignatories: { signature: 'txInfoSignatories(TxInfo txInfo): List<PubKeyHash>', description: 'Get required signers' },
    txInfoValidRange: { signature: 'txInfoValidRange(TxInfo txInfo): Interval', description: 'Get validity time range' },
    txInfoMint: { signature: 'txInfoMint(TxInfo txInfo): Value', description: 'Get minted/burned value' },
    txInfoFee: { signature: 'txInfoFee(TxInfo txInfo): BigInteger', description: 'Get transaction fee in lovelace' },
    txInfoId: { signature: 'txInfoId(TxInfo txInfo): TxId', description: 'Get transaction ID' },
    txInfoRefInputs: { signature: 'txInfoRefInputs(TxInfo txInfo): List<TxInInfo>', description: 'Get reference inputs' },
    txInfoWithdrawals: { signature: 'txInfoWithdrawals(TxInfo txInfo): Map<Credential, BigInteger>', description: 'Get reward withdrawals' },
    txInfoRedeemers: { signature: 'txInfoRedeemers(TxInfo txInfo): Map<ScriptPurpose, PlutusData>', description: 'Get all redeemers' },
    signedBy: { signature: 'signedBy(TxInfo txInfo, byte[] pkh): boolean', description: 'Check if transaction is signed by the given PubKeyHash' },
    getSpendingDatum: { signature: 'getSpendingDatum(ScriptContext ctx): Optional<PlutusData>', description: 'Get optional datum from spending script info' },
    findOwnInput: { signature: 'findOwnInput(ScriptContext ctx): Optional<TxInInfo>', description: 'Find the input being validated by this spending script' },
    ownInputScriptHash: { signature: 'ownInputScriptHash(ScriptContext ctx): byte[]', description: 'Get script credential hash from own input' },
    ownHash: { signature: 'ownHash(ScriptContext ctx): byte[]', description: 'Get own validator script hash' },
    getContinuingOutputs: { signature: 'getContinuingOutputs(ScriptContext ctx): List<TxOut>', description: 'Get outputs paid back to the same script address' },
    valueSpent: { signature: 'valueSpent(TxInfo txInfo): List<Value>', description: 'Collect values of all transaction inputs' },
    valuePaid: { signature: 'valuePaid(TxInfo txInfo, Address addr): List<Value>', description: 'Get values of outputs paid to a specific address' },
    scriptOutputsAt: { signature: 'scriptOutputsAt(TxInfo txInfo, byte[] scriptHash): List<TxOut>', description: 'Get outputs at a script address' },
    findDatum: { signature: 'findDatum(TxInfo txInfo, PlutusData hash): Optional<PlutusData>', description: 'Look up a datum by its hash in the datums map' },
    listIndex: { signature: 'listIndex(ListData list, BigInteger n): PlutusData', description: 'Get the nth element from a list' },
  },
  ListsLib: {
    empty: { signature: 'empty(): List<PlutusData>', description: 'Create an empty list' },
    prepend: { signature: 'prepend(List list, PlutusData element): List', description: 'Prepend an element to the front of a list' },
    length: { signature: 'length(List list): long', description: 'Get the number of elements in a list' },
    isEmpty: { signature: 'isEmpty(List list): boolean', description: 'Check if a list is empty' },
    head: { signature: 'head(List list): PlutusData', description: 'Get the first element of a list' },
    tail: { signature: 'tail(List list): List', description: 'Get all elements except the first' },
    reverse: { signature: 'reverse(List list): List', description: 'Reverse a list' },
    concat: { signature: 'concat(List a, List b): List', description: 'Concatenate two lists' },
    nth: { signature: 'nth(List list, long n): PlutusData', description: 'Get the element at index n' },
    take: { signature: 'take(List list, long n): List', description: 'Take the first n elements' },
    drop: { signature: 'drop(List list, long n): List', description: 'Drop the first n elements' },
    contains: { signature: 'contains(List list, PlutusData target): boolean', description: 'Check if list contains an element (by data equality)' },
    containsInt: { signature: 'containsInt(List list, BigInteger target): boolean', description: 'Check if list contains an integer' },
    containsBytes: { signature: 'containsBytes(List list, byte[] target): boolean', description: 'Check if list contains a byte string' },
    hasDuplicateInts: { signature: 'hasDuplicateInts(List list): boolean', description: 'Check if list has duplicate integers' },
    hasDuplicateBytes: { signature: 'hasDuplicateBytes(List list): boolean', description: 'Check if list has duplicate byte strings' },
    hasDuplicates: { signature: 'hasDuplicates(List list): boolean', description: 'Check if list has any duplicates' },
  },
  MapLib: {
    empty: { signature: 'empty(): Map<PlutusData, PlutusData>', description: 'Create an empty map' },
    lookup: { signature: 'lookup(Map map, PlutusData key): Optional<PlutusData>', description: 'Look up a value by key, returning Optional' },
    member: { signature: 'member(Map map, PlutusData key): boolean', description: 'Check if key exists in the map' },
    insert: { signature: 'insert(Map map, PlutusData key, PlutusData value): Map', description: 'Insert or update a key-value pair' },
    delete: { signature: 'delete(Map map, PlutusData key): Map', description: 'Remove a key from the map' },
    keys: { signature: 'keys(Map map): List<PlutusData>', description: 'Get all keys as a list' },
    values: { signature: 'values(Map map): List<PlutusData>', description: 'Get all values as a list' },
    toList: { signature: 'toList(Map map): Map', description: 'Convert map to pair list' },
    fromList: { signature: 'fromList(PlutusData list): Map', description: 'Create map from pair list' },
    size: { signature: 'size(Map map): long', description: 'Get the number of entries' },
  },
  ValuesLib: {
    lovelaceOf: { signature: 'lovelaceOf(Value value): BigInteger', description: 'Get the ADA amount in lovelace' },
    assetOf: { signature: 'assetOf(Value value, byte[] policyId, byte[] tokenName): BigInteger', description: 'Get quantity of a specific native asset' },
    geqMultiAsset: { signature: 'geqMultiAsset(Value a, Value b): boolean', description: 'Check if value a >= value b for all assets' },
    leq: { signature: 'leq(Value a, Value b): boolean', description: 'Check if value a <= value b' },
    eq: { signature: 'eq(Value a, Value b): boolean', description: 'Check if two values are equal' },
    isZero: { signature: 'isZero(Value value): boolean', description: 'Check if value has no tokens' },
    singleton: { signature: 'singleton(byte[] policyId, byte[] tokenName, BigInteger amount): Value', description: 'Create a Value with a single asset' },
    negate: { signature: 'negate(Value value): Value', description: 'Negate all quantities in a Value' },
    flatten: { signature: 'flatten(Value value): List<PlutusData>', description: 'Flatten Value to list of (policy, token, qty) triples' },
    add: { signature: 'add(Value a, Value b): Value', description: 'Add two Values together' },
    subtract: { signature: 'subtract(Value a, Value b): Value', description: 'Subtract value b from value a' },
    countTokensWithQty: { signature: 'countTokensWithQty(Value mint, byte[] policyId, BigInteger expectedQty): BigInteger', description: 'Count tokens under a policy with a specific quantity' },
    findTokenName: { signature: 'findTokenName(Value mint, byte[] policyId, BigInteger expectedQty): byte[]', description: 'Find token name under a policy with a specific quantity' },
  },
  OutputLib: {
    txOutAddress: { signature: 'txOutAddress(TxOut txOut): Address', description: 'Get the address of a transaction output' },
    txOutValue: { signature: 'txOutValue(TxOut txOut): Value', description: 'Get the value of a transaction output' },
    txOutDatum: { signature: 'txOutDatum(TxOut txOut): OutputDatum', description: 'Get the datum of a transaction output' },
    outputsAt: { signature: 'outputsAt(List<TxOut> outputs, Address address): List<TxOut>', description: 'Filter outputs by address' },
    countOutputsAt: { signature: 'countOutputsAt(List<TxOut> outputs, Address address): long', description: 'Count outputs at an address' },
    uniqueOutputAt: { signature: 'uniqueOutputAt(List<TxOut> outputs, Address address): TxOut', description: 'Get the single output at an address (fails if not exactly one)' },
    outputsWithToken: { signature: 'outputsWithToken(List<TxOut> outputs, byte[] policyId, byte[] tokenName): List<TxOut>', description: 'Filter outputs containing a specific token' },
    valueHasToken: { signature: 'valueHasToken(Value value, byte[] policyId, byte[] tokenName): boolean', description: 'Check if a value contains a specific token' },
    lovelacePaidTo: { signature: 'lovelacePaidTo(List<TxOut> outputs, Address address): BigInteger', description: 'Sum of lovelace paid to an address' },
    paidAtLeast: { signature: 'paidAtLeast(List<TxOut> outputs, Address address, BigInteger min): boolean', description: 'Check if at least min lovelace is paid to an address' },
    getInlineDatum: { signature: 'getInlineDatum(TxOut txOut): PlutusData', description: 'Extract inline datum from output (fails if not inline)' },
    resolveDatum: { signature: 'resolveDatum(TxOut txOut, Map datums): PlutusData', description: 'Resolve datum from output (inline or hash lookup)' },
    findOutputWithToken: { signature: 'findOutputWithToken(List<TxOut> outputs, byte[] scriptHash, byte[] policyId, byte[] tokenName): TxOut', description: 'Find output at script address with specific token' },
    findInputWithToken: { signature: 'findInputWithToken(List<TxInInfo> inputs, byte[] scriptHash, byte[] policyId, byte[] tokenName): TxInInfo', description: 'Find input at script address with specific token' },
  },
  MathLib: {
    abs: { signature: 'abs(BigInteger x): BigInteger', description: 'Absolute value' },
    max: { signature: 'max(BigInteger a, BigInteger b): BigInteger', description: 'Maximum of two integers' },
    min: { signature: 'min(BigInteger a, BigInteger b): BigInteger', description: 'Minimum of two integers' },
    divMod: { signature: 'divMod(BigInteger a, BigInteger b): Tuple2<BigInteger, BigInteger>', description: 'Euclidean division and modulo' },
    quotRem: { signature: 'quotRem(BigInteger a, BigInteger b): Tuple2<BigInteger, BigInteger>', description: 'Truncated division and remainder' },
    pow: { signature: 'pow(BigInteger base, BigInteger exp): BigInteger', description: 'Exponentiation (base^exp)' },
    expMod: { signature: 'expMod(BigInteger base, BigInteger exp, BigInteger mod): BigInteger', description: 'Modular exponentiation' },
    sign: { signature: 'sign(BigInteger x): BigInteger', description: 'Sign of integer (-1, 0, or 1)' },
  },
  IntervalLib: {
    contains: { signature: 'contains(Interval interval, BigInteger point): boolean', description: 'Check if a point is within the interval' },
    always: { signature: 'always(): Interval', description: 'Interval covering all time (-inf, +inf)' },
    after: { signature: 'after(BigInteger t): Interval', description: 'Interval from t to +infinity [t, +inf)' },
    before: { signature: 'before(BigInteger t): Interval', description: 'Interval from -infinity to t (-inf, t]' },
    between: { signature: 'between(BigInteger low, BigInteger high): Interval', description: 'Closed interval [low, high]' },
    never: { signature: 'never(): Interval', description: 'Empty interval (never valid)' },
    isEmpty: { signature: 'isEmpty(Interval interval): boolean', description: 'Check if interval is empty' },
    finiteUpperBound: { signature: 'finiteUpperBound(Interval interval): BigInteger', description: 'Extract finite upper bound (fails if PosInf)' },
    finiteLowerBound: { signature: 'finiteLowerBound(Interval interval): BigInteger', description: 'Extract finite lower bound (fails if NegInf)' },
  },
  CryptoLib: {
    sha2_256: { signature: 'sha2_256(byte[] bs): byte[]', description: 'SHA2-256 hash' },
    sha3_256: { signature: 'sha3_256(byte[] bs): byte[]', description: 'SHA3-256 hash' },
    blake2b_256: { signature: 'blake2b_256(byte[] bs): byte[]', description: 'Blake2b-256 hash' },
    blake2b_224: { signature: 'blake2b_224(byte[] bs): byte[]', description: 'Blake2b-224 hash (28 bytes)' },
    keccak_256: { signature: 'keccak_256(byte[] bs): byte[]', description: 'Keccak-256 hash' },
    verifyEd25519Signature: { signature: 'verifyEd25519Signature(byte[] key, byte[] msg, byte[] sig): boolean', description: 'Verify Ed25519 signature' },
    verifyEcdsaSecp256k1: { signature: 'verifyEcdsaSecp256k1(byte[] vk, byte[] msg, byte[] sig): boolean', description: 'Verify ECDSA secp256k1 signature' },
    verifySchnorrSecp256k1: { signature: 'verifySchnorrSecp256k1(byte[] vk, byte[] msg, byte[] sig): boolean', description: 'Verify Schnorr secp256k1 signature' },
    ripemd_160: { signature: 'ripemd_160(byte[] bs): byte[]', description: 'RIPEMD-160 hash (20 bytes)' },
  },
  ByteStringLib: {
    at: { signature: 'at(byte[] bs, long index): long', description: 'Get byte at index' },
    cons: { signature: 'cons(long byte_, byte[] bs): byte[]', description: 'Prepend a byte' },
    slice: { signature: 'slice(byte[] bs, long start, long length): byte[]', description: 'Extract a slice' },
    length: { signature: 'length(byte[] bs): long', description: 'Byte string length' },
    drop: { signature: 'drop(byte[] bs, long n): byte[]', description: 'Drop first n bytes' },
    take: { signature: 'take(byte[] bs, long n): byte[]', description: 'Take first n bytes' },
    append: { signature: 'append(byte[] a, byte[] b): byte[]', description: 'Concatenate two byte strings' },
    empty: { signature: 'empty(): byte[]', description: 'Empty byte string' },
    equals: { signature: 'equals(byte[] a, byte[] b): boolean', description: 'Byte string equality' },
    lessThan: { signature: 'lessThan(byte[] a, byte[] b): boolean', description: 'Lexicographic less than' },
    lessThanEquals: { signature: 'lessThanEquals(byte[] a, byte[] b): boolean', description: 'Lexicographic less than or equal' },
    integerToByteString: { signature: 'integerToByteString(boolean endian, long width, BigInteger i): byte[]', description: 'Convert integer to byte string' },
    byteStringToInteger: { signature: 'byteStringToInteger(boolean endian, byte[] bs): BigInteger', description: 'Convert byte string to integer' },
    encodeUtf8: { signature: 'encodeUtf8(PlutusData s): byte[]', description: 'Encode string as UTF-8 bytes' },
    decodeUtf8: { signature: 'decodeUtf8(byte[] bs): PlutusData', description: 'Decode UTF-8 bytes to string' },
    serialiseData: { signature: 'serialiseData(PlutusData d): byte[]', description: 'Serialize PlutusData to CBOR bytes' },
    toHex: { signature: 'toHex(byte[] bs): byte[]', description: 'Convert bytes to hex string representation' },
  },
  BitwiseLib: {
    andByteString: { signature: 'andByteString(boolean padding, byte[] a, byte[] b): byte[]', description: 'Bitwise AND' },
    orByteString: { signature: 'orByteString(boolean padding, byte[] a, byte[] b): byte[]', description: 'Bitwise OR' },
    xorByteString: { signature: 'xorByteString(boolean padding, byte[] a, byte[] b): byte[]', description: 'Bitwise XOR' },
    complementByteString: { signature: 'complementByteString(byte[] bs): byte[]', description: 'Bitwise complement (NOT)' },
    readBit: { signature: 'readBit(byte[] bs, long index): boolean', description: 'Read a single bit' },
    writeBits: { signature: 'writeBits(byte[] bs, ListData indices, boolean value): byte[]', description: 'Set bits at given indices' },
    shiftByteString: { signature: 'shiftByteString(byte[] bs, long n): byte[]', description: 'Shift bytes (positive=left, negative=right)' },
    rotateByteString: { signature: 'rotateByteString(byte[] bs, long n): byte[]', description: 'Rotate bytes' },
    countSetBits: { signature: 'countSetBits(byte[] bs): long', description: 'Count number of set bits (popcount)' },
    findFirstSetBit: { signature: 'findFirstSetBit(byte[] bs): long', description: 'Find index of first set bit (-1 if none)' },
  },
  AddressLib: {
    credentialHash: { signature: 'credentialHash(Address address): byte[]', description: 'Extract credential hash from address' },
    isScriptAddress: { signature: 'isScriptAddress(Address address): boolean', description: 'Check if address has a script credential' },
    isPubKeyAddress: { signature: 'isPubKeyAddress(Address address): boolean', description: 'Check if address has a public key credential' },
    paymentCredential: { signature: 'paymentCredential(Address address): Credential', description: 'Extract the payment credential' },
  },
  Builtins: {
    sha2_256: { signature: 'sha2_256(byte[] bs): byte[]', description: 'SHA2-256 hash' },
    sha3_256: { signature: 'sha3_256(byte[] bs): byte[]', description: 'SHA3-256 hash' },
    blake2b_256: { signature: 'blake2b_256(byte[] bs): byte[]', description: 'Blake2b-256 hash' },
    blake2b_224: { signature: 'blake2b_224(byte[] bs): byte[]', description: 'Blake2b-224 hash' },
    trace: { signature: 'trace(String msg, PlutusData value): PlutusData', description: 'Emit trace message and return value' },
    equalsData: { signature: 'equalsData(PlutusData a, PlutusData b): boolean', description: 'Compare two PlutusData values' },
    iData: { signature: 'iData(BigInteger value): PlutusData', description: 'Wrap integer as Data' },
    bData: { signature: 'bData(byte[] bs): PlutusData', description: 'Wrap byte string as Data' },
    unIData: { signature: 'unIData(PlutusData data): BigInteger', description: 'Extract integer from Data' },
    unBData: { signature: 'unBData(PlutusData data): byte[]', description: 'Extract byte string from Data' },
    unListData: { signature: 'unListData(PlutusData data): ListData', description: 'Extract list from Data' },
    unMapData: { signature: 'unMapData(PlutusData data): MapData', description: 'Extract map from Data' },
    headList: { signature: 'headList(PlutusData list): PlutusData', description: 'First element of a list' },
    tailList: { signature: 'tailList(PlutusData list): ListData', description: 'All elements except the first' },
    nullList: { signature: 'nullList(PlutusData list): boolean', description: 'Check if list is empty' },
    mkCons: { signature: 'mkCons(PlutusData elem, PlutusData list): ListData', description: 'Prepend element to list' },
    mkNilData: { signature: 'mkNilData(): ListData', description: 'Create empty list' },
    fstPair: { signature: 'fstPair(PlutusData pair): PlutusData', description: 'First element of a pair' },
    sndPair: { signature: 'sndPair(PlutusData pair): PlutusData', description: 'Second element of a pair' },
    mkPairData: { signature: 'mkPairData(PlutusData fst, PlutusData snd): ConstrData', description: 'Create a pair' },
    error: { signature: 'error(): PlutusData', description: 'Abort script execution' },
    lengthOfByteString: { signature: 'lengthOfByteString(byte[] bs): long', description: 'Length of byte string' },
    indexByteString: { signature: 'indexByteString(byte[] bs, long index): long', description: 'Byte at index' },
    appendByteString: { signature: 'appendByteString(byte[] a, byte[] b): byte[]', description: 'Concatenate byte strings' },
    consByteString: { signature: 'consByteString(long byte_, byte[] bs): byte[]', description: 'Prepend byte' },
    sliceByteString: { signature: 'sliceByteString(long start, long length, byte[] bs): byte[]', description: 'Extract a slice' },
    equalsByteString: { signature: 'equalsByteString(byte[] a, byte[] b): boolean', description: 'Compare byte strings' },
    lessThanByteString: { signature: 'lessThanByteString(byte[] a, byte[] b): boolean', description: 'Lexicographic less than' },
    verifyEd25519Signature: { signature: 'verifyEd25519Signature(byte[] key, byte[] msg, byte[] sig): boolean', description: 'Verify Ed25519 signature' },
    expModInteger: { signature: 'expModInteger(BigInteger base, BigInteger exp, BigInteger mod): BigInteger', description: 'Modular exponentiation' },
  },
};

/** Annotation documentation. */
export const ANNOTATION_DOCS: Record<string, string> = {
  Validator: 'Generic validator — purpose inferred from entrypoint parameter count',
  SpendingValidator: 'Spending validator — validates spending of UTxOs (2 or 3 params: [datum,] redeemer, ctx)',
  MintingPolicy: 'Minting policy — validates minting/burning of tokens (2 params: redeemer, ctx)',
  MintingValidator: 'Minting validator — alias for @MintingPolicy',
  WithdrawValidator: 'Withdraw validator — validates reward withdrawals',
  CertifyingValidator: 'Certifying validator — validates certificate operations',
  VotingValidator: 'Voting validator — validates governance votes (Conway era)',
  ProposingValidator: 'Proposing validator — validates governance proposals (Conway era)',
  MultiValidator: 'Multi-purpose validator — handles multiple script purposes',
  Entrypoint: 'Marks the validator entrypoint method that receives (datum, redeemer, ScriptContext)',
  Param: 'Compile-time parameter — applied before deployment to parameterize the validator',
  OnchainLibrary: 'On-chain library — reusable helper class compiled alongside the validator',
};

/** Ledger type documentation with field lists. */
export const TYPE_DOCS: Record<string, TypeDoc> = {
  ScriptContext: {
    description: 'Script execution context (Plutus V3)',
    fields: ['txInfo: TxInfo', 'redeemer: PlutusData', 'scriptInfo: ScriptInfo'],
  },
  TxInfo: {
    description: 'Transaction information (V3/Conway, 16 fields)',
    fields: [
      'inputs: List<TxInInfo>', 'referenceInputs: List<TxInInfo>', 'outputs: List<TxOut>',
      'fee: BigInteger', 'mint: Value', 'certificates: List<TxCert>',
      'withdrawals: Map<Credential, BigInteger>', 'validRange: Interval',
      'signatories: List<PubKeyHash>', 'redeemers: Map<ScriptPurpose, PlutusData>',
      'datums: Map<DatumHash, PlutusData>', 'id: TxId',
      'votes: Map<Voter, Map<GovernanceActionId, Vote>>',
      'proposalProcedures: List<ProposalProcedure>',
      'currentTreasuryAmount: Optional<BigInteger>', 'treasuryDonation: Optional<BigInteger>',
    ],
  },
  TxInInfo: {
    description: 'Transaction input with resolved output',
    fields: ['outRef: TxOutRef', 'resolved: TxOut'],
  },
  TxOut: {
    description: 'Transaction output',
    fields: ['address: Address', 'value: Value', 'datum: OutputDatum', 'referenceScript: Optional<ScriptHash>'],
  },
  TxOutRef: {
    description: 'Reference to a transaction output',
    fields: ['txId: TxId', 'index: BigInteger'],
  },
  Address: {
    description: 'Cardano address with payment and optional staking credential',
    fields: ['credential: Credential', 'stakingCredential: Optional<StakingCredential>'],
  },
  Value: {
    description: 'Multi-asset value (ADA + native tokens)',
    fields: ['inner: Map<PolicyId, Map<TokenName, BigInteger>>'],
  },
  Interval: {
    description: 'Time interval with lower and upper bounds',
    fields: ['from: IntervalBound', 'to: IntervalBound'],
  },
  IntervalBound: {
    description: 'Interval bound (NegInf, Finite, or PosInf)',
    fields: ['boundType: IntervalBoundType', 'isInclusive: boolean'],
  },
  PubKeyHash: { description: 'Public key hash (28 bytes)', fields: ['hash: byte[]'] },
  ScriptHash: { description: 'Script hash (28 bytes)', fields: ['hash: byte[]'] },
  ValidatorHash: { description: 'Validator hash (28 bytes)', fields: ['hash: byte[]'] },
  PolicyId: { description: 'Minting policy ID (28 bytes)', fields: ['hash: byte[]'] },
  TokenName: { description: 'Token name (0-32 bytes)', fields: ['name: byte[]'] },
  DatumHash: { description: 'Datum hash (32 bytes)', fields: ['hash: byte[]'] },
  TxId: { description: 'Transaction ID (32 bytes)', fields: ['hash: byte[]'] },
  Credential: {
    description: 'Payment credential (sealed interface)',
    fields: ['PubKeyCredential(hash: PubKeyHash)', 'ScriptCredential(hash: ScriptHash)'],
  },
  OutputDatum: {
    description: 'Output datum attachment (sealed interface)',
    fields: ['NoOutputDatum', 'OutputDatumHash(hash: DatumHash)', 'OutputDatumInline(datum: PlutusData)'],
  },
  ScriptInfo: {
    description: 'Script execution info (sealed interface, 6 variants)',
    fields: [
      'MintingScript(policyId: PolicyId)',
      'SpendingScript(txOutRef: TxOutRef, datum: Optional<PlutusData>)',
      'RewardingScript(credential: Credential)',
      'CertifyingScript(index: BigInteger, cert: TxCert)',
      'VotingScript(voter: Voter)',
      'ProposingScript(index: BigInteger, procedure: ProposalProcedure)',
    ],
  },
  PlutusData: { description: 'Base on-chain data type', fields: ['IntData', 'BytesData', 'ConstrData', 'ListData', 'MapData'] },
  BigInteger: { description: 'Arbitrary-precision integer (on-chain integer type)', fields: [] },
  JulcList: { description: 'On-chain list type (JulcList<T>)', fields: [] },
  JulcMap: { description: 'On-chain map type (JulcMap<K,V>)', fields: [] },
  Tuple2: { description: 'Pair type', fields: ['first: A', 'second: B'] },
  Tuple3: { description: 'Triple type', fields: ['first: A', 'second: B', 'third: C'] },
};

/** Instance methods for ledger record types (record accessor methods). */
export interface InstanceMethodInfo {
  name: string;
  returnType: string;
  detail: string;
  insertText?: string; // snippet for methods with params
  signature?: string;  // full signature for parameter hints (e.g. "add(BigInteger a, BigInteger b): BigInteger")
}

export const INSTANCE_METHODS: Record<string, InstanceMethodInfo[]> = {
  ScriptContext: [
    { name: 'txInfo', returnType: 'TxInfo', detail: 'Transaction info' },
    { name: 'redeemer', returnType: 'PlutusData', detail: 'Redeemer data' },
    { name: 'scriptInfo', returnType: 'ScriptInfo', detail: 'Script execution info' },
  ],
  TxInfo: [
    { name: 'inputs', returnType: 'List<TxInInfo>', detail: 'Transaction inputs' },
    { name: 'referenceInputs', returnType: 'List<TxInInfo>', detail: 'Reference inputs' },
    { name: 'outputs', returnType: 'List<TxOut>', detail: 'Transaction outputs' },
    { name: 'fee', returnType: 'BigInteger', detail: 'Transaction fee' },
    { name: 'mint', returnType: 'Value', detail: 'Minted/burned value' },
    { name: 'certificates', returnType: 'List<TxCert>', detail: 'Certificates' },
    { name: 'withdrawals', returnType: 'Map<Credential, BigInteger>', detail: 'Reward withdrawals' },
    { name: 'validRange', returnType: 'Interval', detail: 'Validity time range' },
    { name: 'signatories', returnType: 'List<PubKeyHash>', detail: 'Required signers' },
    { name: 'redeemers', returnType: 'Map<ScriptPurpose, PlutusData>', detail: 'All redeemers' },
    { name: 'datums', returnType: 'Map<DatumHash, PlutusData>', detail: 'Datum map' },
    { name: 'id', returnType: 'TxId', detail: 'Transaction ID' },
    { name: 'votes', returnType: 'Map<Voter, Map<GovernanceActionId, Vote>>', detail: 'Governance votes' },
    { name: 'proposalProcedures', returnType: 'List<ProposalProcedure>', detail: 'Governance proposals' },
    { name: 'currentTreasuryAmount', returnType: 'Optional<BigInteger>', detail: 'Treasury amount' },
    { name: 'treasuryDonation', returnType: 'Optional<BigInteger>', detail: 'Treasury donation' },
  ],
  TxOut: [
    { name: 'address', returnType: 'Address', detail: 'Output address' },
    { name: 'value', returnType: 'Value', detail: 'Output value' },
    { name: 'datum', returnType: 'OutputDatum', detail: 'Output datum' },
    { name: 'referenceScript', returnType: 'Optional<ScriptHash>', detail: 'Reference script' },
  ],
  TxInInfo: [
    { name: 'outRef', returnType: 'TxOutRef', detail: 'Output reference' },
    { name: 'resolved', returnType: 'TxOut', detail: 'Resolved output' },
  ],
  TxOutRef: [
    { name: 'txId', returnType: 'TxId', detail: 'Transaction ID' },
    { name: 'index', returnType: 'BigInteger', detail: 'Output index' },
  ],
  Address: [
    { name: 'credential', returnType: 'Credential', detail: 'Payment credential' },
    { name: 'stakingCredential', returnType: 'Optional<StakingCredential>', detail: 'Staking credential' },
  ],
  Value: [
    { name: 'lovelaceOf', returnType: 'BigInteger', detail: 'ADA amount in lovelace' },
    { name: 'assetOf', returnType: 'BigInteger', detail: 'Get asset quantity', insertText: 'assetOf(${1:policyId}, ${2:tokenName})' },
    { name: 'containsPolicy', returnType: 'boolean', detail: 'Check policy exists', insertText: 'containsPolicy(${1:policyId})' },
    { name: 'isEmpty', returnType: 'boolean', detail: 'Check if value is empty' },
  ],
  Interval: [
    { name: 'from', returnType: 'IntervalBound', detail: 'Lower bound' },
    { name: 'to', returnType: 'IntervalBound', detail: 'Upper bound' },
  ],
  IntervalBound: [
    { name: 'boundType', returnType: 'IntervalBoundType', detail: 'Bound type (NegInf/Finite/PosInf)' },
    { name: 'isInclusive', returnType: 'boolean', detail: 'Is bound inclusive' },
  ],
  PubKeyHash: [{ name: 'hash', returnType: 'byte[]', detail: 'Raw hash bytes' }],
  ScriptHash: [{ name: 'hash', returnType: 'byte[]', detail: 'Raw hash bytes' }],
  ValidatorHash: [{ name: 'hash', returnType: 'byte[]', detail: 'Raw hash bytes' }],
  PolicyId: [{ name: 'hash', returnType: 'byte[]', detail: 'Policy ID bytes' }],
  TokenName: [{ name: 'name', returnType: 'byte[]', detail: 'Token name bytes' }],
  DatumHash: [{ name: 'hash', returnType: 'byte[]', detail: 'Datum hash bytes' }],
  TxId: [{ name: 'hash', returnType: 'byte[]', detail: 'Transaction hash bytes' }],
  Tuple2: [
    { name: 'first', returnType: 'A', detail: 'First element' },
    { name: 'second', returnType: 'B', detail: 'Second element' },
  ],
  Tuple3: [
    { name: 'first', returnType: 'A', detail: 'First element' },
    { name: 'second', returnType: 'B', detail: 'Second element' },
    { name: 'third', returnType: 'C', detail: 'Third element' },
  ],
  List: [
    { name: 'head', returnType: 'T', detail: 'First element' },
    { name: 'tail', returnType: 'List<T>', detail: 'All except first' },
    { name: 'get', returnType: 'T', detail: 'Element at index', insertText: 'get(${1:index})' },
    { name: 'size', returnType: 'BigInteger', detail: 'Number of elements' },
    { name: 'isEmpty', returnType: 'boolean', detail: 'Check if empty' },
    { name: 'contains', returnType: 'boolean', detail: 'Check if contains element', insertText: 'contains(${1:elem})' },
    { name: 'reverse', returnType: 'List<T>', detail: 'Reversed list' },
    { name: 'concat', returnType: 'List<T>', detail: 'Concatenate lists', insertText: 'concat(${1:other})' },
    { name: 'prepend', returnType: 'List<T>', detail: 'Prepend element', insertText: 'prepend(${1:elem})' },
    { name: 'take', returnType: 'List<T>', detail: 'Take first n', insertText: 'take(${1:n})' },
    { name: 'drop', returnType: 'List<T>', detail: 'Drop first n', insertText: 'drop(${1:n})' },
    { name: 'map', returnType: 'List<R>', detail: 'Transform each element', insertText: 'map(${1:e} -> ${2:expr})' },
    { name: 'filter', returnType: 'List<T>', detail: 'Filter elements', insertText: 'filter(${1:e} -> ${2:condition})' },
    { name: 'any', returnType: 'boolean', detail: 'Any element matches predicate', insertText: 'any(${1:e} -> ${2:condition})' },
    { name: 'all', returnType: 'boolean', detail: 'All elements match predicate', insertText: 'all(${1:e} -> ${2:condition})' },
    { name: 'find', returnType: 'Optional<T>', detail: 'Find first matching element', insertText: 'find(${1:e} -> ${2:condition})' },
    { name: 'foldl', returnType: 'R', detail: 'Left fold over elements', insertText: 'foldl(${1:init}, (${2:acc}, ${3:e}) -> ${4:expr})' },
  ],
  Map: [
    { name: 'get', returnType: 'V', detail: 'Get value by key (fails on miss)', insertText: 'get(${1:key})' },
    { name: 'lookup', returnType: 'Optional<V>', detail: 'Look up value by key', insertText: 'lookup(${1:key})' },
    { name: 'containsKey', returnType: 'boolean', detail: 'Check if key exists', insertText: 'containsKey(${1:key})' },
    { name: 'size', returnType: 'BigInteger', detail: 'Number of entries' },
    { name: 'isEmpty', returnType: 'boolean', detail: 'Check if empty' },
    { name: 'keys', returnType: 'List<K>', detail: 'All keys' },
    { name: 'values', returnType: 'List<V>', detail: 'All values' },
    { name: 'insert', returnType: 'Map<K,V>', detail: 'Insert key-value pair', insertText: 'insert(${1:key}, ${2:value})' },
    { name: 'delete', returnType: 'Map<K,V>', detail: 'Delete key', insertText: 'delete(${1:key})' },
  ],
  Optional: [
    { name: 'get', returnType: 'T', detail: 'Get value (fails if empty)' },
    { name: 'isEmpty', returnType: 'boolean', detail: 'Check if empty' },
    { name: 'isPresent', returnType: 'boolean', detail: 'Check if present' },
  ],
};
