package com.bloxbean.julc.cli.cmd.verify;

import com.bloxbean.julc.cli.JulcVersionProvider;
import com.bloxbean.julc.cli.cmd.blueprint.ArtifactCommand;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/** Deterministically generates a pinned Blaster workspace from a CIP-57 blueprint. */
public final class VerificationProjectGenerator {

    static final String LEAN_VERSION = "v4.24.0";
    static final String BLASTER_REV = "083bae7971414d894b56b5bbf4108c63e17bc42a";
    static final String PLUTUS_CORE_REV = "7cf5a78c54b9694ef093bf49edb5d3799b2a49c9";
    static final String LEDGER_API_REV = "5dab3c43f042b8735b6d067223baaa8d32ed28a1";
    static final String GENERATED_MARKER = "Generated by `julc verify init`; regenerate instead of editing.";
    private static final ObjectMapper JSON = new ObjectMapper()
            .enable(SerializationFeature.INDENT_OUTPUT)
            .enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);
    private static final Set<Integer> SUPPORTED_BUILTINS = supportedBuiltins();
    private static final Set<String> LEAN_RESERVED = Set.of(
            "abbrev", "axiom", "class", "def", "deriving", "else", "end",
            "example", "export", "extends", "for", "from", "fun", "if",
            "import", "in", "inductive", "instance", "let", "match",
            "namespace", "open", "opaque", "private", "protected",
            "structure", "syntax", "theorem", "then", "universe", "where",
            "with");
    private static final Set<String> RESERVED_TYPE_NAMES = Set.of(
            "ByteString", "Data", "Integer", "IsData", "ScriptContext");
    private static final Set<String> USER_OWNED_FILES = Set.of("SecurityProperty.lean");

    private VerificationProjectGenerator() { }

    public static GenerationResult generate(
            Path blueprintFile,
            String validatorTitle,
            String purpose,
            int fuel,
            Path outputDirectory,
            boolean force) throws Exception {
        if (fuel <= 0) {
            throw new IllegalArgumentException("Verification fuel must be positive");
        }
        if (!purpose.equals("spending") && !purpose.equals("minting")) {
            throw new IllegalArgumentException("Purpose must be spending or minting");
        }
        if (!Files.isRegularFile(blueprintFile)) {
            throw new IllegalArgumentException("Blueprint not found: " + blueprintFile);
        }

        JsonNode blueprint = JSON.readTree(blueprintFile.toFile());
        String plutusVersion = blueprint.path("preamble").path("plutusVersion").asText();
        if (!"v3".equalsIgnoreCase(plutusVersion)) {
            throw new UnsupportedVerificationException(
                    "Only Plutus V3 blueprints are supported, found '" + plutusVersion + "'");
        }

        var artifact = ArtifactCommand.inspect(blueprintFile, validatorTitle);
        ensureSupportedBuiltins(artifact.builtins());

        JsonNode validator = exactValidator(blueprint, validatorTitle);
        boolean hasDatum = validator.has("datum") && validator.path("datum").has("schema");
        if (purpose.equals("spending") && !hasDatum) {
            throw new UnsupportedVerificationException(
                    "Spending verification requires a datum schema in the selected validator");
        }
        if (purpose.equals("minting") && hasDatum) {
            throw new UnsupportedVerificationException(
                    "Minting verification cannot use a validator entry with a datum schema");
        }
        SchemaGeneration schemas = generateSchemas(blueprint.path("definitions"), validator);
        String leanId = leanTypeName(validatorTitle);
        String artifactId = artifact.artifactId();

        Path output = outputDirectory.toAbsolutePath().normalize();
        if (Files.exists(output) && !force) {
            try (var children = Files.list(output)) {
                if (children.findAny().isPresent()) {
                    throw new IllegalArgumentException(
                            "Output directory is not empty; use --force to overwrite generated files: "
                                    + output);
                }
            }
        }

        Map<String, String> files = new LinkedHashMap<>();
        files.put("lean-toolchain", "leanprover/lean4:" + LEAN_VERSION + "\n");
        files.put("lakefile.lean", lakefile());
        files.put("GeneratedSchemas.lean", schemas.source());
        files.put("PropertyTemplates.lean", propertyTemplates());
        files.put("CheckedExecution.lean", checkedExecution());
        files.put("SecurityProperty.lean", securityProperty());
        files.put(leanId + "Verification.lean",
                validatorModule(leanId, artifactId, purpose, fuel));
        files.put("artifacts/" + artifactId + ".compiledCode.hex",
                artifact.compiledCode() + "\n");
        files.put("config/blaster-builtins.txt",
                "# " + GENERATED_MARKER + "\n0-88\n92-93\n");
        files.put("scripts/verify.sh",
                verifyScript(leanId, artifactId, artifact.compiledCodeSha256()));
        files.put("README.md", readme(leanId, validatorTitle, purpose));
        files.put("verification-manifest.json",
                manifest(blueprint, artifact, purpose, fuel, schemas.names()));

        writeAtomically(output, files);
        return new GenerationResult(output, artifactId, leanId, files.keySet().stream().toList());
    }

    static void ensureSupportedBuiltins(List<ArtifactCommand.BuiltinUse> builtins)
            throws UnsupportedVerificationException {
        for (var builtin : builtins) {
            if (!SUPPORTED_BUILTINS.contains(builtin.flatTag())) {
                throw new UnsupportedVerificationException(
                        "Builtin " + builtin.name() + " (tag " + builtin.flatTag()
                                + ") is unsupported by the pinned Blaster profile");
            }
        }
    }

    static SchemaGeneration generateSchemas(JsonNode definitions, JsonNode validator)
            throws UnsupportedVerificationException {
        if (!definitions.isObject()) {
            throw new UnsupportedVerificationException("Blueprint definitions must be an object");
        }

        Set<String> roots = new LinkedHashSet<>();
        collectEntrySchemaRoot(validator.path("datum").path("schema"), roots);
        collectEntrySchemaRoot(validator.path("redeemer").path("schema"), roots);
        if (roots.isEmpty()) {
            throw new UnsupportedVerificationException(
                    "Validator has no named datum or redeemer schema references");
        }

        Map<String, JsonNode> all = new LinkedHashMap<>();
        definitions.fields().forEachRemaining(entry -> all.put(entry.getKey(), entry.getValue()));
        Set<String> needed = new LinkedHashSet<>();
        for (String root : roots.stream().sorted().toList()) {
            collectNeeded(root, all, needed, new HashSet<>());
        }

        Map<String, String> names = new LinkedHashMap<>();
        Set<String> normalized = new HashSet<>();
        for (String name : needed) {
            JsonNode schema = all.get(name);
            if (primitiveType(schema) != null) {
                continue;
            }
            if (!hasIdentifierCharacters(name)) {
                throw new UnsupportedVerificationException(
                        "Schema name cannot form a Lean identifier: '" + name + "'");
            }
            String leanName = leanTypeName(name);
            if (RESERVED_TYPE_NAMES.contains(leanName)) {
                throw new UnsupportedVerificationException(
                        "Schema name conflicts with generated Lean imports at '" + leanName + "'");
            }
            if (!normalized.add(leanName)) {
                throw new UnsupportedVerificationException(
                        "Schema names collide after Lean normalization at '" + leanName + "'");
            }
            names.put(name, leanName);
        }

        var source = new StringBuilder();
        source.append("/- ").append(GENERATED_MARKER).append(" -/\n")
                .append("import CardanoLedgerApi.IsData.Class\n\n")
                .append("namespace JulcGenerated.Schemas\n\n")
                .append("open CardanoLedgerApi.IsData.Class\n")
                .append("open PlutusCore.ByteString (ByteString)\n")
                .append("open PlutusCore.Data (Data)\n")
                .append("open PlutusCore.Integer (Integer)\n\n");

        for (String original : names.keySet()) {
            source.append(generateDefinition(original, names.get(original), all, names));
        }
        source.append("end JulcGenerated.Schemas\n");
        return new SchemaGeneration(source.toString(), names);
    }

    private static String generateDefinition(
            String original,
            String typeName,
            Map<String, JsonNode> definitions,
            Map<String, String> names) throws UnsupportedVerificationException {
        JsonNode schema = definitions.get(original);
        JsonNode alternatives = schema.path("anyOf");
        if (!alternatives.isArray() || alternatives.isEmpty()) {
            throw unsupported(original, schema);
        }

        List<Constructor> constructors = new ArrayList<>();
        Set<String> constructorNames = new HashSet<>();
        Set<Integer> constructorIndexes = new HashSet<>();
        for (JsonNode alternative : alternatives) {
            if (!"constructor".equals(alternative.path("dataType").asText())) {
                throw unsupported(original, alternative);
            }
            if (!alternative.path("index").canConvertToInt()) {
                throw new UnsupportedVerificationException(
                        "Constructor index is missing for schema definition '" + original + "'");
            }
            int constructorIndex = alternative.path("index").asInt();
            if (constructorIndex < 0 || !constructorIndexes.add(constructorIndex)) {
                throw new UnsupportedVerificationException(
                        "Constructor indexes must be unique and nonnegative in schema definition '"
                                + original + "'");
            }
            String title = alternative.path("title").asText(typeName);
            if (!hasIdentifierCharacters(title)) {
                throw new UnsupportedVerificationException(
                        "Constructor title cannot form a Lean identifier in schema definition '"
                                + original + "'");
            }
            String ctorName = leanTypeName(title);
            if (!constructorNames.add(ctorName)) {
                throw new UnsupportedVerificationException(
                        "Constructor names collide in schema definition '" + original + "'");
            }
            List<Field> fields = fields(original, alternative.path("fields"), definitions, names);
            constructors.add(new Constructor(ctorName, constructorIndex, fields));
        }

        boolean structure = constructors.size() == 1 && !constructors.getFirst().fields().isEmpty();
        var out = new StringBuilder();
        if (structure) {
            Constructor ctor = constructors.getFirst();
            out.append("structure ").append(typeName).append(" where\n");
            for (Field field : ctor.fields()) {
                out.append("  ").append(field.name()).append(" : ").append(field.type()).append("\n");
            }
            out.append("deriving Repr\n\n")
                    .append("instance : IsData ").append(typeName).append(" where\n")
                    .append("  toData x := mkDataConstr ").append(ctor.index()).append(" ")
                    .append(dataList(ctor.fields(), field -> "IsData.toData x." + field.name()))
                    .append("\n")
                    .append("  fromData\n")
                    .append(fromDataBranch(ctor, "some { " + assignments(ctor.fields()) + " }"))
                    .append("  | _ => none\n\n");
        } else {
            out.append("inductive ").append(typeName).append(" where\n");
            for (Constructor ctor : constructors) {
                out.append("  | ").append(ctor.name());
                for (Field field : ctor.fields()) {
                    out.append(" (").append(field.name()).append(" : ").append(field.type()).append(")");
                }
                out.append("\n");
            }
            out.append("deriving Repr\n\n")
                    .append("instance : IsData ").append(typeName).append(" where\n")
                    .append("  toData\n");
            for (Constructor ctor : constructors) {
                out.append("  | .").append(ctor.name());
                for (Field field : ctor.fields()) {
                    out.append(" ").append(field.name());
                }
                out.append(" => mkDataConstr ").append(ctor.index()).append(" ")
                        .append(dataList(ctor.fields(), field -> "IsData.toData " + field.name()))
                        .append("\n");
            }
            out.append("  fromData\n");
            for (Constructor ctor : constructors) {
                String value = "some (." + ctor.name()
                        + ctor.fields().stream().map(field -> " " + field.name())
                        .reduce("", String::concat) + ")";
                out.append(fromDataBranch(ctor, value));
            }
            out.append("  | _ => none\n\n");
        }
        return out.toString();
    }

    private static String fromDataBranch(Constructor ctor, String success) {
        var out = new StringBuilder("  | Data.Constr ")
                .append(ctor.index()).append(" ")
                .append(dataList(ctor.fields(), field -> "r_" + field.name()))
                .append(" =>\n");
        if (ctor.fields().isEmpty()) {
            return out.append("      ").append(success).append("\n").toString();
        }
        out.append("      match ")
                .append(ctor.fields().stream()
                        .map(field -> "IsData.fromData r_" + field.name())
                        .reduce((a, b) -> a + ", " + b).orElseThrow())
                .append(" with\n")
                .append("      | ")
                .append(ctor.fields().stream().map(field -> "some " + field.name())
                        .reduce((a, b) -> a + ", " + b).orElseThrow())
                .append(" => ").append(success).append("\n")
                .append("      | ")
                .append(ctor.fields().stream().map(field -> "_")
                        .reduce((a, b) -> a + ", " + b).orElseThrow())
                .append(" => none\n");
        return out.toString();
    }

    private static List<Field> fields(
            String owner,
            JsonNode fields,
            Map<String, JsonNode> definitions,
            Map<String, String> names) throws UnsupportedVerificationException {
        if (!fields.isArray()) {
            throw new UnsupportedVerificationException(
                    "Constructor fields must be an array in schema definition '" + owner + "'");
        }
        List<Field> result = new ArrayList<>();
        Set<String> fieldNames = new HashSet<>();
        int index = 0;
        for (JsonNode field : fields) {
            String rawName = field.path("title").asText("field" + index);
            if (!hasIdentifierCharacters(rawName)) {
                throw new UnsupportedVerificationException(
                        "Field title cannot form a Lean identifier in schema definition '"
                                + owner + "'");
            }
            String name = leanFieldName(rawName);
            if (!fieldNames.add(name)) {
                throw new UnsupportedVerificationException(
                        "Field names collide in schema definition '" + owner + "'");
            }
            result.add(new Field(name, schemaType(field, definitions, names, owner)));
            index++;
        }
        return result;
    }

    private static String schemaType(
            JsonNode field,
            Map<String, JsonNode> definitions,
            Map<String, String> names,
            String owner) throws UnsupportedVerificationException {
        String ref = field.path("$ref").asText(null);
        if (ref == null) {
            String primitive = primitiveType(field);
            if (primitive != null) {
                return primitive;
            }
            throw new UnsupportedVerificationException(
                    "Inline or unsupported field schema in definition '" + owner + "'");
        }
        String referenced = referenceName(ref);
        JsonNode target = definitions.get(referenced);
        if (target == null) {
            throw new UnsupportedVerificationException("Unknown schema reference '" + ref + "'");
        }
        String primitive = primitiveType(target);
        if (primitive != null) {
            return primitive;
        }
        String named = names.get(referenced);
        if (named == null) {
            throw unsupported(referenced, target);
        }
        return named;
    }

    private static String primitiveType(JsonNode schema) {
        return switch (schema.path("dataType").asText()) {
            case "integer" -> "Integer";
            case "bytes" -> "ByteString";
            default -> null;
        };
    }

    private static void collectEntrySchemaRoot(JsonNode schema, Set<String> roots)
            throws UnsupportedVerificationException {
        if (schema.isMissingNode()) {
            return;
        }
        String ref = schema.path("$ref").asText(null);
        if (ref == null) {
            throw new UnsupportedVerificationException(
                    "Entrypoint datum/redeemer schema must use a named definition reference");
        }
        roots.add(referenceName(ref));
    }

    private static void collectNeeded(
            String name,
            Map<String, JsonNode> definitions,
            Set<String> needed,
            Set<String> active) throws UnsupportedVerificationException {
        JsonNode schema = definitions.get(name);
        if (schema == null) {
            throw new UnsupportedVerificationException("Unknown schema definition '" + name + "'");
        }
        if (active.contains(name)) {
            throw new UnsupportedVerificationException(
                    "Recursive schema definition is not supported: '" + name + "'");
        }
        if (needed.contains(name)) {
            return;
        }
        active.add(name);
        if (primitiveType(schema) == null) {
            JsonNode anyOf = schema.path("anyOf");
            if (!anyOf.isArray()) {
                throw unsupported(name, schema);
            }
            for (JsonNode alternative : anyOf) {
                JsonNode fields = alternative.path("fields");
                if (!fields.isArray()) {
                    throw unsupported(name, alternative);
                }
                for (JsonNode field : fields) {
                    String ref = field.path("$ref").asText(null);
                    if (ref == null) {
                        if (primitiveType(field) == null) {
                            throw new UnsupportedVerificationException(
                                    "Inline field schema is unsupported in definition '" + name + "'");
                        }
                    } else {
                        collectNeeded(referenceName(ref), definitions, needed, active);
                    }
                }
            }
        }
        active.remove(name);
        needed.add(name);
    }

    private static JsonNode exactValidator(JsonNode blueprint, String title) {
        List<JsonNode> matches = new ArrayList<>();
        blueprint.path("validators").forEach(node -> {
            if (title.equals(node.path("title").asText(null))) {
                matches.add(node);
            }
        });
        if (matches.size() != 1) {
            throw new IllegalArgumentException(
                    "Expected exactly one validator titled '" + title + "', found " + matches.size());
        }
        return matches.getFirst();
    }

    private static String manifest(
            JsonNode blueprint,
            ArtifactCommand.ArtifactMetadata artifact,
            String purpose,
            int fuel,
            Map<String, String> schemaNames) throws IOException {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("schemaVersion", 1);
        root.put("generatedBy", "julc verify init");
        root.put("julcVersion", JulcVersionProvider.VERSION);
        root.put("project", blueprint.path("preamble").path("title").asText());
        root.put("validatorTitle", artifact.title());
        root.put("artifactId", artifact.artifactId());
        root.put("compiledCodeSha256", artifact.compiledCodeSha256());
        root.put("cardanoScriptHash", artifact.cardanoScriptHash());
        root.put("uplcVersion", artifact.uplcVersion());
        root.put("scriptPurpose", purpose);
        root.put("plutusLanguage", "PlutusV3");
        root.put("protocolVersion", 11);
        root.put("builtinSemanticsVariant", "E");
        root.put("artifactFormat", "double_cbor_hex");
        root.put("fuel", fuel);
        root.put("leanVersion", "4.24.0");
        root.put("z3Version", "4.15.2");
        root.put("dependencies", Map.of(
                "Lean-blaster", BLASTER_REV,
                "PlutusCoreBlaster", PLUTUS_CORE_REV,
                "CardanoLedgerApiBlaster", LEDGER_API_REV));
        root.put("builtins", artifact.builtins());
        root.put("schemas", schemaNames.entrySet().stream()
                .map(entry -> Map.of("cip57", entry.getKey(), "lean", entry.getValue()))
                .toList());
        root.put("properties", List.of(Map.of(
                "id", artifact.artifactId() + ".security-property",
                "result", "COULD-NOT-EVALUATE",
                "reason", "property-not-specialized")));
        return JSON.writeValueAsString(root) + "\n";
    }

    private static String lakefile() {
        return """
                /- Generated by `julc verify init`; dependency pins are security inputs. -/
                import Lake
                open Lake DSL

                package «julc-generated-verification» where
                  moreGlobalServerArgs := #["--threads=4"]
                  moreLeanArgs := #["--threads=4"]

                require Blaster from git
                  "https://github.com/input-output-hk/Lean-blaster" @
                    "%s"
                require PlutusCore from git
                  "https://github.com/input-output-hk/PlutusCoreBlaster" @
                    "%s"
                require «CardanoLedgerApi» from git
                  "https://github.com/input-output-hk/CardanoLedgerApiBlaster" @
                    "%s"

                lean_lib «GeneratedVerificationSupport» where
                  roots := #[`GeneratedSchemas, `PropertyTemplates, `CheckedExecution,
                    `SecurityProperty]
                """.formatted(BLASTER_REV, PLUTUS_CORE_REV, LEDGER_API_REV);
    }

    private static String checkedExecution() {
        return """
                /- Generated by `julc verify init`; explicit semantics and exhaustion API. -/
                import PlutusCore.Default
                import PlutusCore.UPLC.CekMachine
                import PlutusCore.UPLC.Utils

                namespace JulcGenerated.CheckedExecution

                open PlutusCore.Default
                open PlutusCore.UPLC.CekMachine
                open PlutusCore.UPLC.Term

                inductive CheckedResult where
                  | finished : State → CheckedResult
                  | stepExhausted : State → CheckedResult
                deriving Repr

                def runStepsChecked
                    (semanticsVariant : BuiltinSemanticsVariant)
                    (state : State) : Nat → CheckedResult
                  | 0 =>
                      match state with
                      | .Halt _ | .Error => .finished state
                      | _ => .stepExhausted state
                  | Nat.succ remaining =>
                      match state with
                      | .Halt _ | .Error => .finished state
                      | _ => runStepsChecked semanticsVariant
                          (step semanticsVariant state) remaining

                def executeProgramChecked
                    (semanticsVariant : BuiltinSemanticsVariant)
                    (program : Program)
                    (params : List Term)
                    (fuel : Nat) : CheckedResult :=
                  match program with
                  | .Program _ body => runStepsChecked semanticsVariant
                      (initialState (applyParams body params)) fuel

                /-- Generated Plutus V3/PV11 workspaces select semantics variant E. -/
                def executePlutusV3Pv11Checked : Program → List Term → Nat → CheckedResult :=
                  executeProgramChecked .defaultFunSemanticsVariantE

                def isSuccessful : CheckedResult → Prop
                  | .finished (.Halt _) => True
                  | _ => False

                def isEvaluationError : CheckedResult → Prop
                  | .finished .Error => True
                  | _ => False

                def isStepExhausted : CheckedResult → Prop
                  | .stepExhausted _ => True
                  | _ => False

                end JulcGenerated.CheckedExecution
                """;
    }

    private static String propertyTemplates() {
        return """
                /- Generated by `julc verify init`; reusable predicates, not theorem claims. -/
                import CardanoLedgerApi.V3

                namespace JulcGenerated.PropertyTemplates

                open CardanoLedgerApi.IsData.Class
                open CardanoLedgerApi.V3
                open PlutusCore.ByteString (ByteString)
                open PlutusCore.Data (Data)
                open PlutusCore.Integer (Integer)

                def firstSignerAuthorized (authority : ByteString) (ctx : ScriptContext) : Prop :=
                  match ctx.scriptContextTxInfo.txInfoSignatories with
                  | signer :: _ => signer = authority
                  | [] => False

                def firstInputValuePreserved (ctx : ScriptContext) : Prop :=
                  match ctx.scriptContextTxInfo.txInfoInputs,
                      ctx.scriptContextTxInfo.txInfoOutputs with
                  | input :: _, output :: _ =>
                      input.txInInfoResolved.txOutValue = output.txOutValue
                  | _, _ => False

                def firstOutputCommitsTo
                    (ref : CardanoLedgerApi.V3.Tx.TxOutRef)
                    (nextState : Integer)
                    (ctx : ScriptContext) : Prop :=
                  match ctx.scriptContextTxInfo.txInfoOutputs with
                  | output :: _ => output.txOutDatum =
                      .OutputDatum (Data.Constr 0 [IsData.toData ref, Data.I nextState])
                  | [] => False

                end JulcGenerated.PropertyTemplates
                """;
    }

    private static String validatorModule(
            String leanId, String artifactId, String purpose, int fuel) {
        String prepInputs = purpose.equals("spending") ? "spendingInputs" : "mintingInputs";
        return """
                /- Generated by `julc verify init`; specialize the property before claiming proof. -/
                import PlutusCore.UPLC
                import CardanoLedgerApi.V3
                import Blaster
                import GeneratedSchemas
                import PropertyTemplates
                import CheckedExecution
                import SecurityProperty

                namespace JulcGenerated.%s

                open CardanoLedgerApi.V3
                open PlutusCore.UPLC.Utils
                open JulcGenerated.UserProperty

                #import_uplc validator PlutusV3 double_cbor_hex
                  "artifacts/%s.compiledCode.hex"
                #prep_uplc appliedValidator validator %s %d

                /-- An explicit, currently unproved obligation; no theorem is generated. -/
                def verificationObligation : Prop :=
                  ∀ ctx : ScriptContext,
                    PlutusCore.UPLC.Utils.isSuccessful (appliedValidator.prop ctx) →
                    securityProperty ctx

                end JulcGenerated.%s
                """.formatted(leanId, artifactId, prepInputs, fuel, leanId);
    }

    private static String securityProperty() {
        return """
                /- Created by `julc verify init`; user-owned and preserved by `--force`. -/
                import CardanoLedgerApi.V3
                import PropertyTemplates

                namespace JulcGenerated.UserProperty

                open CardanoLedgerApi.V3

                /-- Replace with the reviewed, contract-specific security property. -/
                def securityProperty (_ctx : ScriptContext) : Prop := False

                end JulcGenerated.UserProperty
                """;
    }

    private static String verifyScript(
            String leanId, String artifactId, String compiledCodeSha256) {
        return """
                #!/usr/bin/env bash
                set -euo pipefail

                SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
                VERIFY_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
                if [[ -d "${HOME}/.elan/bin" ]]; then
                  export PATH="${HOME}/.elan/bin:${PATH}"
                fi
                cd "${VERIFY_DIR}"

                for tool in lake lean rg z3 git xxd; do
                  command -v "${tool}" >/dev/null 2>&1 || {
                    echo "COULD-NOT-EVALUATE: missing ${tool}" >&2
                    exit 2
                  }
                done

                [[ "$(lean --version | head -n 1)" == *"4.24.0"* ]] || {
                  echo "COULD-NOT-EVALUATE: expected Lean 4.24.0" >&2
                  exit 2
                }
                [[ "$(z3 --version)" == *"4.15.2"* ]] || {
                  echo "COULD-NOT-EVALUATE: expected Z3 4.15.2" >&2
                  exit 2
                }

                if command -v sha256sum >/dev/null 2>&1; then
                  actual_artifact_hash="$(tr -d '[:space:]' < artifacts/%s.compiledCode.hex | xxd -r -p | sha256sum | awk '{print $1}')"
                else
                  command -v shasum >/dev/null 2>&1 || {
                    echo "COULD-NOT-EVALUATE: missing SHA-256 tool" >&2
                    exit 2
                  }
                  actual_artifact_hash="$(tr -d '[:space:]' < artifacts/%s.compiledCode.hex | xxd -r -p | shasum -a 256 | awk '{print $1}')"
                fi
                [[ "${actual_artifact_hash}" == "%s" ]] || {
                  echo "COULD-NOT-EVALUATE: compiledCode artifact hash mismatch" >&2
                  exit 2
                }

                if rg -n '(^|[[:space:]])(sorry|admit)([[:space:]]|$)' --glob '*.lean' .; then
                  echo "COULD-NOT-EVALUATE: generated project contains sorry or admit" >&2
                  exit 2
                fi

                lake build GeneratedVerificationSupport
                while IFS=' ' read -r package expected; do
                  actual="$(git -C ".lake/packages/${package}" rev-parse HEAD)"
                  [[ "${actual}" == "${expected}" ]] || {
                    echo "COULD-NOT-EVALUATE: ${package} revision mismatch" >&2
                    exit 2
                  }
                done <<'PINS'
                Blaster %s
                PlutusCore %s
                CardanoLedgerApi %s
                PINS
                mkdir -p .lake/build/lib/lean
                lake env lean -o .lake/build/lib/lean/GeneratedSchemas.olean GeneratedSchemas.lean
                lake env lean -o .lake/build/lib/lean/PropertyTemplates.olean PropertyTemplates.lean
                lake env lean -o .lake/build/lib/lean/CheckedExecution.olean CheckedExecution.lean
                lake env lean -o .lake/build/lib/lean/SecurityProperty.olean SecurityProperty.lean
                lake env lean -o .lake/build/lib/lean/%sVerification.olean %sVerification.lean

                echo "COULD-NOT-EVALUATE: workspace compiles; specialize securityProperty and add a theorem plus negative control"
                exit 2
                """.formatted(artifactId, artifactId, compiledCodeSha256,
                BLASTER_REV, PLUTUS_CORE_REV, LEDGER_API_REV, leanId, leanId);
    }

    private static String readme(String leanId, String validatorTitle, String purpose) {
        return """
                # Generated JuLC verification workspace

                This workspace was generated for `%s` (%s) by `julc verify init`.
                The artifact, profile, fuel, and dependency pins are recorded in
                `verification-manifest.json`.

                Required tools are Lean 4.24.0/Lake, Z3 4.15.2, Git, and ripgrep.

                `GeneratedSchemas.lean` contains strict CIP-57-derived `IsData`
                instances. `PropertyTemplates.lean` contains reusable predicates, and
                `CheckedExecution.lean` fixes semantics variant E while keeping step
                exhaustion distinct from evaluation failure.
                `SecurityProperty.lean` is user-owned and deliberately defines
                `securityProperty` as `False`; `--force` regeneration preserves this file.
                Replace it with a reviewed threat-model property, add a Blaster theorem and
                a vulnerable negative control to `%sVerification.lean`, then run:

                ```bash
                lake update
                scripts/verify.sh
                ```

                A successful compilation is still reported as `COULD-NOT-EVALUATE` until the
                property is specialized and proved. Solver-valid claims must be labeled
                `SMT-VALID`; ordinary Lean proofs may be labeled `KERNEL-PROVED`.
                """.formatted(validatorTitle, purpose, leanId);
    }

    private static void writeAtomically(Path output, Map<String, String> files)
            throws IOException {
        Path parent = output.getParent();
        if (parent == null) {
            throw new IllegalArgumentException("Output directory must have a parent");
        }
        Files.createDirectories(parent);
        Path staging = Files.createTempDirectory(parent, ".julc-verify-init-");
        try {
            for (var entry : files.entrySet()) {
                Path target = staging.resolve(entry.getKey());
                Files.createDirectories(target.getParent());
                Files.writeString(target, entry.getValue());
                if (entry.getKey().equals("scripts/verify.sh")) {
                    target.toFile().setExecutable(true, false);
                }
            }

            if (!Files.exists(output)) {
                Files.move(staging, output, StandardCopyOption.ATOMIC_MOVE);
                staging = null;
            } else {
                for (String relative : files.keySet()) {
                    Path source = staging.resolve(relative);
                    Path target = output.resolve(relative);
                    if (USER_OWNED_FILES.contains(relative) && Files.exists(target)) {
                        continue;
                    }
                    Files.createDirectories(target.getParent());
                    Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING,
                            StandardCopyOption.COPY_ATTRIBUTES);
                }
            }
        } finally {
            if (staging != null && Files.exists(staging)) {
                deleteTree(staging);
            }
        }
    }

    private static void deleteTree(Path root) throws IOException {
        try (var paths = Files.walk(root)) {
            for (Path path : paths.sorted((a, b) -> b.compareTo(a)).toList()) {
                Files.deleteIfExists(path);
            }
        }
    }

    private static UnsupportedVerificationException unsupported(String name, JsonNode schema) {
        String kind = schema.path("dataType").asText(
                schema.has("anyOf") ? "constructor" : "unknown");
        return new UnsupportedVerificationException(
                "Unsupported schema form '" + kind + "' in definition '" + name + "'");
    }

    private static String referenceName(String ref) throws UnsupportedVerificationException {
        String prefix = "#/definitions/";
        if (!ref.startsWith(prefix) || ref.length() == prefix.length()) {
            throw new UnsupportedVerificationException("Unsupported schema reference '" + ref + "'");
        }
        return ref.substring(prefix.length())
                .replace("~1", "/")
                .replace("~0", "~");
    }

    private static String leanTypeName(String raw) {
        StringBuilder result = new StringBuilder();
        for (String part : raw.split("[^A-Za-z0-9]+")) {
            if (!part.isEmpty()) {
                result.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
            }
        }
        if (result.isEmpty()) {
            result.append("GeneratedType");
        }
        if (Character.isDigit(result.charAt(0))) {
            result.insert(0, 'T');
        }
        return result.toString();
    }

    private static boolean hasIdentifierCharacters(String raw) {
        return raw != null && raw.chars().anyMatch(Character::isLetterOrDigit);
    }

    private static String leanFieldName(String raw) {
        String typeName = leanTypeName(raw);
        String result = Character.toLowerCase(typeName.charAt(0)) + typeName.substring(1);
        if (LEAN_RESERVED.contains(result.toLowerCase(Locale.ROOT))) {
            result += "Field";
        }
        return result;
    }

    private static String dataList(List<Field> fields, FieldRenderer renderer) {
        return "[" + fields.stream().map(renderer::render)
                .reduce((a, b) -> a + ", " + b).orElse("") + "]";
    }

    private static String assignments(List<Field> fields) {
        return fields.stream().map(field -> field.name() + " := " + field.name())
                .reduce((a, b) -> a + ", " + b).orElse("");
    }

    private static Set<Integer> supportedBuiltins() {
        Set<Integer> result = new HashSet<>();
        for (int tag = 0; tag <= 88; tag++) {
            result.add(tag);
        }
        result.add(92);
        result.add(93);
        return Set.copyOf(result);
    }

    @FunctionalInterface
    private interface FieldRenderer {
        String render(Field field);
    }

    private record Field(String name, String type) { }
    private record Constructor(String name, int index, List<Field> fields) { }

    public record SchemaGeneration(String source, Map<String, String> names) { }
    public record GenerationResult(
            Path outputDirectory, String artifactId, String leanNamespace, List<String> files) { }
}
