package com.bloxbean.cardano.julc.decompiler.lift;

import com.bloxbean.cardano.julc.core.DefaultFun;
import com.bloxbean.cardano.julc.core.Term;

/**
 * Recognizes Z-combinator patterns used for loops and recursion.
 * <p>
 * The Z-combinator pattern generated by UplcGenerator is:
 * <pre>
 * Apply(Lam(name, expr),
 *   Apply(Lam("f", Apply(branch, branch)),   // fix = \f -> branch branch
 *     Lam(name, recBody)))                     // where branch = \x -> f (\v -> x x v)
 * </pre>
 * <p>
 * Where branch = Lam("x", Apply(Var(2), Lam("v", Apply(Apply(Var(2), Var(2)), Var(1)))))
 * <p>
 * This is equivalent to: let name = fix(\name -> recBody) in expr
 * <p>
 * The recognizer classifies the recursive body as:
 * - ForEach: uses NullList for termination, HeadList/TailList for traversal
 * - While: uses a condition for termination
 * - General recursion: anything else
 */
public final class LoopRecognizer {

    private LoopRecognizer() {}

    /**
     * Try to recognize a Z-combinator (fix-point) pattern.
     * Returns null if not a Z-combinator.
     */
    public static ZCombinatorResult match(Term term) {
        // Pattern: Apply(Lam(name, expr), Apply(fix, Lam(name, recBody)))
        // where fix = Lam("f", Apply(branch, branch))
        // and branch = Lam("x", Apply(Var(2), Lam("v", Apply(Apply(Var(2), Var(2)), Var(1)))))

        // First, this must be a Let: Apply(Lam(name, expr), value)
        if (!(term instanceof Term.Apply outerApp)) return null;
        if (!(outerApp.function() instanceof Term.Lam outerLam)) return null;

        String name = outerLam.paramName();
        Term expr = outerLam.body();
        Term value = outerApp.argument();

        // value must be Apply(fix, Lam(name, recBody))
        if (!(value instanceof Term.Apply fixApp)) return null;

        // fix must be Lam("f", Apply(branch, branch))
        Term fix = fixApp.function();
        Term recLam = fixApp.argument();

        if (!isZCombinator(fix)) return null;
        if (!(recLam instanceof Term.Lam rl)) return null;

        String recParamName = rl.paramName();
        Term recBody = rl.body();

        return new ZCombinatorResult(name, recParamName, recBody, expr);
    }

    /**
     * Check if a term is the Z-combinator:
     * Lam("f", Apply(
     *   Lam("x", Apply(Var(2), Lam("v", Apply(Apply(Var(2), Var(2)), Var(1))))),
     *   Lam("x", Apply(Var(2), Lam("v", Apply(Apply(Var(2), Var(2)), Var(1)))))))
     */
    private static boolean isZCombinator(Term term) {
        if (!(term instanceof Term.Lam fixLam)) return false;
        if (!(fixLam.body() instanceof Term.Apply app)) return false;

        return isOmegaBranch(app.function()) && isOmegaBranch(app.argument());
    }

    /**
     * Check if a term is an omega branch:
     * Lam("x", Apply(Var(2), Lam("v", Apply(Apply(Var(2), Var(2)), Var(1)))))
     */
    private static boolean isOmegaBranch(Term term) {
        if (!(term instanceof Term.Lam lam)) return false;
        if (!(lam.body() instanceof Term.Apply app)) return false;

        // app.function() should be Var with index 2 (references "f" from Z-combinator)
        if (!(app.function() instanceof Term.Var v && v.name().index() == 2)) return false;

        // app.argument() should be Lam("v", Apply(Apply(Var(2), Var(2)), Var(1)))
        if (!(app.argument() instanceof Term.Lam innerLam)) return false;
        if (!(innerLam.body() instanceof Term.Apply app2)) return false;
        if (!(app2.function() instanceof Term.Apply app3)) return false;
        if (!(app3.function() instanceof Term.Var v1 && v1.name().index() == 2)) return false;
        if (!(app3.argument() instanceof Term.Var v2 && v2.name().index() == 2)) return false;
        if (!(app2.argument() instanceof Term.Var v3 && v3.name().index() == 1)) return false;

        return true;
    }

    /**
     * Classify what kind of loop/recursion the body represents.
     */
    public static LoopKind classifyBody(Term recBody) {
        // Check for list iteration pattern: NullList used as termination condition
        if (usesBuiltin(recBody, DefaultFun.NullList)
                && usesBuiltin(recBody, DefaultFun.HeadList)
                && usesBuiltin(recBody, DefaultFun.TailList)) {
            return LoopKind.FOR_EACH;
        }
        // If there's a conditional check but no list operations, it's a while loop
        if (usesBuiltin(recBody, DefaultFun.IfThenElse)) {
            return LoopKind.WHILE;
        }
        return LoopKind.GENERAL_RECURSION;
    }

    private static boolean usesBuiltin(Term term, DefaultFun fun) {
        return switch (term) {
            case Term.Builtin b -> b.fun() == fun;
            case Term.Apply a -> usesBuiltin(a.function(), fun) || usesBuiltin(a.argument(), fun);
            case Term.Lam l -> usesBuiltin(l.body(), fun);
            case Term.Force f -> usesBuiltin(f.term(), fun);
            case Term.Delay d -> usesBuiltin(d.term(), fun);
            case Term.Constr c -> c.fields().stream().anyMatch(f -> usesBuiltin(f, fun));
            case Term.Case cs -> usesBuiltin(cs.scrutinee(), fun)
                    || cs.branches().stream().anyMatch(b -> usesBuiltin(b, fun));
            default -> false;
        };
    }

    public enum LoopKind {
        FOR_EACH,
        WHILE,
        GENERAL_RECURSION
    }

    public record ZCombinatorResult(String name, String recParamName, Term recBody, Term continuation) {}
}
